version: "3"
services:
    app:
       build:
           context: .
    nginx: 
        image: nginx:1.20.2
        volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
        - app
        ports:
        - "1337:80"